### ISSUE TITLE
Version 0.4.11 has disappeared from npm?

### ISSUE THREAD

**Issue by nathanpeck** [mongodb/js-bson#147] opened 2015-10-06 14:16 UTC
Version 0.4.11 has mysteriously disappeared from npm, and is causing errors in all dependent packages that depended on that version. I opened a ticket with npm: https://github.com/npm/npm/issues/9859

If possible perhaps you could reupload this missing package version?

**Comment by christkv** [comment] 2015-10-06 14:17
I had to pull it due to a very bad regression causing undefined values not be serialized as nulls.

**Comment by christkv** [comment] 2015-10-06 14:18
are you having a hard dependency ? as the driver does ~0.4 for BSON

**Comment by nathanpeck** [comment] 2015-10-06 14:21
It was shrink wrapped on 0.4.11 for us. Updating it to the latest BSON module now.

Thanks for the clarification. I checked the changelog earlier but did not see any update there about the regression so I didn't realize this was a bad release. If possible could you add a note there about the regression just in case anyone else has their packages shrinkwrapped on this bad version?

**Comment by mwawrusch** [comment] 2015-10-07 00:23
Hi Christian, can you please release any other version as 0.4.11 - spent almost a day so far on tracking this down and fixing it in our deployment.

**Comment by christkv** [comment] 2015-10-07 05:33
@mwawrusch that's actually not possible, NPM forbids using the version number again.

**Comment by YouriT** [comment] 2015-10-07 07:14
I agree with @mwawrusch was a amazing loss of time. Sad you cannot put it back @christkv...

**Comment by christkv** [comment] 2015-10-07 07:16
yeah they changed that, it used to be you could --force it but thats no longer possible to seems to be a philosophical decision on part of the NPM team.

**Comment by nathanpeck** [comment] 2015-10-07 14:18
@christkv In my opinion a better approach here would have been to use the [deprecation feature of NPM](https://docs.npmjs.com/cli/deprecate) to leave the broken module version in place but place a warning in the install logs every time someone installs it.

This way there would have been more clarity into the issue and less wasted time for all who happened to shrinkwrap their packages on version 0.4.11

**Comment by christkv** [comment] 2015-10-07 14:23
that would have been the best way yeah but I did not know they changed the politics on unpublished publish so was caught completely off guard. I can't even put back the original 0.4.11 version and mark it deprecated.

**Comment by christkv** [comment] 2015-10-15 07:09
I'm closing the issue

**Closed by christkv** 2015-10-15 07:09 UTC
