### ISSUE TITLE
[NODE-1599] Why does bson always allocate 17 MB memory?

### ISSUE THREAD

**Issue by dannyharding10** [mongodb/js-bson#448] opened 2021-07-22 16:48 UTC
I am working on my Node.js server trying to decrease the amount of memory it uses and found a 17 MB object that was coming from bson. It appears to be coming from this line:

https://github.com/mongodb/js-bson/blob/6ceaa05a68c1a89e43b3b6d0002e5bab69e2613f/src/bson.ts#L107-L111

I understand this is most likely necessary, but I'm curious as to why?  I also wanted to raise this issue in case for some reason it is not necessary to hold onto this 17 MB of memory, then we could figure out a way to change this. Thanks in advance!

**Comment by dariakp** [comment] 2021-07-22 18:43
Hi there, thank you for reaching out to us. We have actually had a ticket for a while to decrease the size for web deployments: https://jira.mongodb.org/browse/NODE-1599, it seems to have gone stale so I put it back in our triage queue to revisit in the next team meeting. The original reasoning was related to performance, but we'll revisit to see if that is still applicable. Please follow the ticket linked above, we should have an update soon.

**Comment by dannyharding10** [comment] 2021-07-22 19:07
Thanks for commenting! I'm working in a node environment, so this update wouldn't change anything for me, which is fine. I was curious why it was necessary at all. According to that issue, it's looks like it's for "performance reasons". Could you provide any more details about that? I'm mostly curious!

**Comment by dariakp** [comment] 2021-07-23 15:00
@dannyharding10 The specific number - 17MB - is the max size of a bson document, as to why we allocate at all, the decision was made a very long time ago, so it's difficult to tell the exact reasoning, but presumably there was some performance cost to creating a lot of smaller buffers vs using the preallocated shared one. We'll have to do some work to investigate whether that is actually true when we schedule NODE-1599. We're curious, too :)

**Comment by dannyharding10** [comment] 2021-07-23 19:21
@dariakp this is exactly the answer I was looking for, thank you!

**Comment by dariakp** [comment] 2021-07-23 19:48
You're welcome! Any objections to me closing this issue on github and just keeping track in jira?

**Comment by dannyharding10** [comment] 2021-07-23 19:50
I just would like to know the final resolution, and I don't know if GitHub would notify me if the issue is closed. If I'm still able to get notified then no problem!

**Comment by dariakp** [comment] 2021-07-23 19:52
No problem, I'll keep it open for now then

**Comment by Pigotz** [comment] 2021-08-31 09:05
I've been experiencing this issue as well but in my case the problem is not the allocation of 17MB (_I'm quite fine with them_) but the inability of the GC to clean them.

If you instantiate a buffer of 17MB inside the global scope and refer to it inside local functions, there will always be a reference to it and the GC won't be able to collect it. As referenced by @dannyharding10 .

You can reproduce this behavior with a simple script:

```javascript
const BSON = require('bson');
const {writeHeapSnapshot} = require('v8');

console.log(BSON.serialize(42));

writeHeapSnapshot();
```

By analyzing the Heap snapshot with Chrome Dev Tools, you'll be able to see that 17MB of memory stay allocated as long as the program is running

In my case, the solution was to remove the global instance and instantiate the same buffer inside any function that needs it. I know that this approach might lead to performance pitfalls but at least I have my heap memory cleaned up after using the BSON library.

```patch
diff --git a/node_modules/bson/lib/bson.js b/node_modules/bson/lib/bson.js
index 625ddfc..895a9c8 100644
--- a/node_modules/bson/lib/bson.js
+++ b/node_modules/bson/lib/bson.js
@@ -78,21 +78,21 @@ Object.defineProperty(exports, "LongWithoutOverridesClass", { enumerable: true,
 /** @internal */
 // Default Max Size
 const MAXSIZE = 1024 * 1024 * 17;
-// Current Internal Temporary Serialization Buffer
-let buffer = buffer_1.Buffer.alloc(MAXSIZE);
+// // Current Internal Temporary Serialization Buffer
+// let buffer = buffer_1.Buffer.alloc(MAXSIZE);
 /**
  * Sets the size of the internal serialization buffer.
  *
  * @param size - The desired size for the internal serialization buffer
  * @public
  */
-function setInternalBufferSize(size) {
-    // Resize the internal serialization buffer if needed
-    if (buffer.length < size) {
-        buffer = buffer_1.Buffer.alloc(size);
-    }
-}
-exports.setInternalBufferSize = setInternalBufferSize;
+// function setInternalBufferSize(size) {
+//     // Resize the internal serialization buffer if needed
+//     if (buffer.length < size) {
+//         buffer = buffer_1.Buffer.alloc(size);
+//     }
+// }
+// exports.setInternalBufferSize = setInternalBufferSize;
 /**
  * Serialize a Javascript object.
  *
@@ -101,6 +101,8 @@ exports.setInternalBufferSize = setInternalBufferSize;
  * @public
  */
 function serialize(object, options = {}) {
+    let buffer = buffer_1.Buffer.alloc(MAXSIZE);
+    
     // Unpack the options
     const checkKeys = typeof options.checkKeys === 'boolean' ? options.checkKeys : false;
     const serializeFunctions = typeof options.serializeFunctions === 'boolean' ? options.serializeFunctions : false;
@@ -130,6 +132,8 @@ exports.serialize = serialize;
  * @public
  */
 function serializeWithBufferAndIndex(object, finalBuffer, options = {}) {
+    let buffer = buffer_1.Buffer.alloc(MAXSIZE);
+
     // Unpack the options
     const checkKeys = typeof options.checkKeys === 'boolean' ? options.checkKeys : false;
     const serializeFunctions = typeof options.serializeFunctions === 'boolean' ? options.serializeFunctions : false;

```

**Comment by dariakp** [comment] 2021-08-31 15:26
@Pigotz Thank you for adding more context for the problem as well as a suggested fix. We'll definitely keep it in mind when we schedule the full investigation in NODE-1599!

**Comment by Pigotz** [comment] 2021-08-31 15:58
You're welcome @dariakp !

Just to give some more suggestions: if you really need to keep that buffer globally scoped, you could think about exposing a method to manipulate it properly.
Right now, developers can only increase its size but are not able to shrink it, nor to reset it.

Concluding, I see to possible ways here:
- Either that buffer object gets locally scoped, losing on performance
- Or some more manipulation functions get exposed from the library in order to let the user decide how to deal with it, without losing any speed, hopefully

Hope my comment will be helpful in your investigation :raised_hands:

**Comment by bajanam** [comment] 2021-12-16 21:03
This issue is being tracked in Jira, please continue all conversations in the corresponding Jira ticket.  Thanks!

**Closed by bajanam** 2021-12-16 21:03 UTC
Labels: tracked-in-jira
